### ISSUE TITLE
Not finding QT: maemo5

### ISSUE THREAD

**Issue by clort81** [maemo-leste-extras/dorian#2]
How do you build Dorian?

/big/src/dorian$ qmake
Project MESSAGE: Warning: unknown QT: maemo5
Project MESSAGE: Warning: unknown QT: x11extras

Trying to build 'CatorisePlus' and using Dorian as an example.

include <QtMaemo5/QMaemo5InformationBox>
Not finding anything.  

Cheers!

**Comment by petterreinholdtsen** [comment]
I built it natively by add deb-src entries to /etc/apt/sources.list, fetching the code using 'apt-get build-dep dorian; apt install devscripts; apt-get source dorian; cd dorian-*; debuild'.   Perhaps it can work for you too?

**Comment by MerlijnWajer** [comment]
I think since this issue was reported, a lot has changes, and with the right dev package, this will work.

Try `dpkg-buildpackage -b -uc` and see what packages it claims it needs, install them, and you should be good to go.
